import enum

class JobType(enum.Enum):
    BRAND_DOWNLOAD = "BRAND_DOWNLOAD"
    BRAND_TOTAL_ADS_UPDATE = "BRAND_TOTAL_ADS_UPDATE"
    CAR_DOWNLOAD_INFO = "CAR_DOWNLOAD_INFO"
    CAR_INFO = "CAR_INFO"